name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  release:
    name: Build release.nix (${{ matrix.target }})

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: Install Nix
        uses: cachix/install-nix-action@7ab6e7fd29da88e74b1e314a4ae9ac6b5cda3801 # v31

      - name: Run tests
        env:
          TARGET: ${{ matrix.target }}
        run: |
          nix build \
            --no-link \
            --print-build-logs \
            --print-out-paths \
            --show-trace \
            --file release.nix \
            "outputs.perTarget.$TARGET" \
            >> "$GITHUB_STEP_SUMMARY"
