name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  release:
    name: Build release.nix (${{ matrix.target }})

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Nix
        uses: cachix/install-nix-action@91a071959513ca103b54280ac0bef5b825791d4d # v31

      - name: Run tests
        env:
          TARGET: ${{ matrix.target }}
        run: |
          nix build \
            --no-link \
            --print-build-logs \
            --print-out-paths \
            --show-trace \
            --file release.nix \
            "outputs.perTarget.$SYSTEM" \
            >> "$GITHUB_STEP_SUMMARY"
